blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('view/<int:pk>', BlogPostDetailView.as_view(), name='blog_post_detail_view'),
    path('', cache_page(600)(BlogListView.as_view()), name='blog')
]

djangoCourseWork/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import BlogPostView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('mailing.urls', namespace='mailing')),
    path('', BlogPostView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
]

mailing/urls.py
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    path('mailings', MailingListVeiw.as_view(), name='mailings'),
    path('create/', MailCreateView.as_view(), name='create_mailing'),
    path('view/<int:pk>', MailDetailView.as_view(), name='view'),
    path('update/<int:pk>', MailUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MailDeleteView.as_view(), name='delete'),
    path('change_status/<int:pk>', change_status, name='change_status'),
    path('create_mail_message/', MessageCreateView.as_view(), name='message_create')
]

mailing/models.py
from django.db import models
from djangoCourseWork import settings
from clients.models import Client
import datetime

class Mail(models.Model):

    SEND_CHOICES = (
        ('daily', 'раз в день'),
        ('weekly', 'раз в неделю'),
        ('monthly', 'раз в месяц'),
    )
    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
        ('blocked', 'Заблокирована')
    )
    title = models.CharField(max_length=100, verbose_name='Название рассылки')
    start_date = models.DateTimeField(verbose_name="Дата начала рассылки", null=True, blank=True)
    end_date = models.DateTimeField(verbose_name="Дата окончания рассылки", null=True, blank=True)
    send_time = models.TimeField(verbose_name="Время длительности рассылки")
    send_frequency = models.CharField(max_length=10, choices=SEND_CHOICES, verbose_name="Частота рассылки")
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='created', verbose_name="Статус рассылки")
    clients = models.ManyToManyField(Client, verbose_name="Клиенты", related_name="mailings")
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                             verbose_name="Пользователь")

    def __str__(self):
        return self.title


class Message(models.Model):

    subject = models.CharField(max_length=255, verbose_name='тема')
    body = models.TextField(verbose_name='сообщение')
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, null=True, blank=True, verbose_name='рассылка')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

mailing/forms.py
from django import forms
from mailing.models import Mail, Message


class MailingForm(forms.ModelForm):

    class Meta:
        model = Mail
        exclude = ('user', 'status',)


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        exclude = ('mail',)

mailing/views.py
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from mailing.models import Mail, Message
from mailing.forms import MailingForm, MessageForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin



class MailingListVeiw(ListView):
    model = Mail
    template_name = 'mailing/mail_list.html'
    extra_context = {'title': 'Список рассылок'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if not self.request.user.is_staff:
            queryset = queryset.filter(user=self.request.user)
        return queryset


class MailCreateView(LoginRequiredMixin, CreateView):
    model = Mail
    form_class = MailingForm
    success_url = reverse_lazy('mailing:message_create')

    def form_valid(self, form):
        if form.is_valid():
            mailing = form.save()
            mailing.user_id = self.request.user
            mailing.save()

        return super().form_valid(form)



class MailDetailView(DetailView):
    model = Mail


class MailUpdateView(LoginRequiredMixin, UpdateView):
    model = Mail
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailings')
    template_name = 'mailing/mail_update_form.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mail, Message, form=MessageForm, extra=0)
        context_data['formset'] = MessageFormset()
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)



class MailDeleteView(LoginRequiredMixin, DeleteView):
    model = Mail
    success_url = reverse_lazy('mailing:mailings')

def change_status(request, pk):

    mail = get_object_or_404(Mail, pk=pk)
    print(mail.status)
    if mail.status != 'blocked':
        mail.status = 'blocked'
        print(mail.status)
    else:
        mail.status = 'created'
    mail.save()
    return redirect(reverse('mailing:mailings'))


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:mailings')

    def form_valid(self, form):
        if form.is_valid():
            mailing = Mail.objects.filter(user_id=self.request.user.id).order_by('-creation_date')[0]
            print(form)
            message = form.save()
            message.mail_id = mailing.id
            message.save()

        return super().form_valid(form)

mailing/templates/mailing/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% include 'mailing/includes/inc_main_menu.html' %}

{% block content %}

{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md" style="margin: 0px 0px 10px 10px">
            <p class="text" >SkyStore</p>
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                            <a href="{% url 'blog:blog_post_detail_view' object.pk %}"
                               class="btn btn-sm btn-outline-secondary">Читать пост</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-3">
            <div class="card-body">
                <p class="text">Общее количество рассылок: {{ mailings_quantity }}</p>
                <p class="text">Количество активных рассылок: {{ active_mailings }}</p>
                <p class="text">Количество уникальных клиентов для рассылок: {{ clients }}</p>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mail_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p class="text">
                            Вы действительно хотите удалить "{{ object }}"?
                        </p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:mailings' %}" class="btn btn-outline-primary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mail_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6" style="margin: 0px 0px 10px 10px">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object }}
                    </h3>
                </div>
                <div class="card-body">
                    <p class="text">
                        Время начала рассылки: {{ object.start_date }};<br>
                        Время окончания рассылки: {{ object.end_date }};<br>
                        Времмя длительности рассылки: {{ object.send_time }};<br>
                        Частота рассылки: {{ object.send_frequency }};
                        Статус рассылки: {{ object.status }};<br>

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mail_form.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Создание рассылки</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать рассылку</button>
                        <a href="{% url 'home' %}" class="btn btn-outline-primary">Отмена</a>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

mailing/templates/mailing/mail_list.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                        </div>
                        <div class="card-body">
                            {{ object.title }}
                        </div>
                        <div class="card-footer">
                            <div class="btn-group">
                                {% if request.user.is_staff and request.user.id != object.user_id%}
                                    <a href="{% url 'mailing:change_status' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">block</a>
                                    <a href="{% url 'mailing:view' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">view</a>
                                {% else %}
                                    <a href="{% url 'mailing:view' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">view</a>
                                    {% if request.user.id == object.user_id %}
                                        <a href="{% url 'mailing:edit' object.pk %}"
                                           class="btn btn-sm btn-outline-secondary">edit</a>
                                        <a href="{% url 'mailing:delete' object.pk %}"
                                           class="btn btn-sm btn-outline-danger">delete</a>
                                    {% else %}
                                        <a href="{% url 'mailing:view' object.pk %}"
                                           class="btn btn-sm btn-outline-secondary">edit</a>
                                        <a href="{% url 'mailing:view' object.pk %}"
                                           class="btn btn-sm btn-outline-danger">delete</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-2">
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:create_mailing' %}">
                    Добавить рассылку
                </a>
            {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'home' %}">
                    Добавить рассылку
                </a>
            {% endif %}
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mail_update_form.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>Создание рассылки</h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                            <a href="{% url 'home' %}" class="btn btn-outline-primary">Отмена</a>
                        </div>
                    </div>
                </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Введите сообщение</h3>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Создание рассылки</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать сообщение</button>
                        <a href="{% url 'home' %}" class="btn btn-outline-primary">Отмена</a>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}