blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('view/<int:pk>', BlogPostDetailView.as_view(), name='blog_post_detail_view'),
    path('', cache_page(600)(BlogListView.as_view()), name='blog')
]

djangoCourseWork/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import BlogPostView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('mailing.urls', namespace='mailing')),
    path('', BlogPostView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import *
from django.views.generic import TemplateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/new_password/', get_new_password, name='new_password'),
    path('verification/<uid>/<token>/', Verification.as_view(), name='verification'),
    path('confirm_email', TemplateView.as_view(template_name='users/confirm_email.html'),
         name='confirm_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    username = None

    email = models.EmailField(unique=True)
    email_verificated = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30, verbose_name='Имя', null=True, blank=True)
    last_name = models.CharField(max_length=30, verbose_name='Фамилия', null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from users.models import CustomUser
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from users.email_funcs import verification


class UserRegisterForm(UserCreationForm):

    class Meta:

        model = CustomUser
        fields = ('email', 'password1', 'password2')


class UserAuthenticationForm(AuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username is not None and password:
            self.user_cache = authenticate(
                self.request,
                username=username,
                password=password
            )
            if not self.user_cache.email_verificated:
                verification(self.request, self.user_cache)
                raise ValidationError(
                    'Подтвердите почту чтобы войти в аккаунт',
                    code='invalid_login'
                )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class UserProfileForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.shortcuts import redirect
from django.contrib.auth import logout, get_user_model
from users.models import CustomUser
from django.views.generic import CreateView, UpdateView
from django.views import View
from users.forms import UserRegisterForm, UserProfileForm, UserAuthenticationForm
from django.urls import reverse_lazy, reverse
from string import ascii_letters as letters, digits
from random import sample
from users.email_funcs import _send_mail_password
from django.utils.http import urlsafe_base64_decode
from django.core.exceptions import ValidationError
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth.views import LoginView


User = get_user_model()


class Verification(View):


    def get(self, request, uid, token):
        user = self.get_user(uid)

        if token_generator.check_token(user, token):
            user.email_verificated = True
            user.save()
            return redirect('users:login')
        return redirect('users:invalid_verify')


    @staticmethod
    def get_user(uid):
        try:
            uid = urlsafe_base64_decode(uid).decode()
            user = User.objects.get(id=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


def get_new_password(request):
    password = ''.join(sample(letters + digits, 10))
    request.user.set_password(password)
    request.user.save()
    _send_mail_password(password, request.user.email)
    return redirect(reverse('users:logout'))


class RegisterView(CreateView):
    model = CustomUser
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = CustomUser
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def logout_view(request):
    logout(request)
    return redirect('users:login')


class MyLoginView(LoginView):

    form_class = UserAuthenticationForm
    template_name = 'users/login.html'

users/templates/users/confirm_email.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row" style="margin: 0px 0px 10px 10px">
        <p>Подтвердите свою почту чтобы завершить регистрацию</p>
    </div>
{% endblock %}

users/templates/users/customuser_form.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <div class="col-12">
            <form class="row" style="margin: 0px 0px 10px 10px" method="post" enctype="multipart/form-data">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>
                                Профиль
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'users:new_password'%}" class="btn btn-danger">Сгенерировать пароль</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/email_verification.html
Здравствуйте {{ user }},
перейдите по ссылке для подтверждения почты:
http://127.0.0.1:8000{% url 'users:verification' uid=uid token=token %}

users/templates/users/invalid_verify.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div style="margin: 0px 0px 10px 10px">
        <p>Ссылка недествительна, запросите новую</p>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <div class="col-6">
            <form class="row" style="margin: 0px 0px 10px 10px" method="post" enctype="multipart/form-data">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>
                                Вход
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Войти</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <div class="col-12">
            <form class="row" style="margin: 0px 0px 10px 10px" method="post" enctype="multipart/form-data">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>
                                Регистрация
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Регистрация</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}